name: Build and Deploy

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: cp -rv * /var/www/html
      continue-on-error: true